spring:
    profiles.active: default
    profiles: default

    main:
        show_banner: true

    datasource:
        platform: hsqldb

    jpa:
        hibernate:
            ddl-auto: create-drop

info:
    app:
        name: Starter Service
        description: Starter provides REST services
        version: 1.0.0

starter:
    datasource:
        url: jdbc:hsqldb:file:data/starterdb
        username: sa
        password:
        driverClassName: org.hsqldb.jdbcDriver

